#!/usr/bin/env bash

config="$HOME/.local/share/forg.conf" # Sources filenames and extensions
logs="$HOME/.cache/forg.logs"

DRYMODE=false
KILLDUPLICATE=false
method=""
src_directory=""
output_directory=""

readonly config

function help() {
  cat <<EOF
File Organizer
Usage: $0 [options] <method> <source-directory> <dest-directory>
Options:
  -d, --dry       Preview actions
  -r, --rm        Remove duplicate files
  -h, --help      Show this message
EOF
}

move() {
  find "$src_directory" -type f -print0 | while IFS= read -r -d $'\0' file; do
    filename=$(basename "$file")
    file_tag="${filename%%\%*}"
    extension="${filename##*.}"
    destination_subpath=""

    case "$method" in
    ftp)
      destination_subpath="${ftp[$extension]}"
      ;;
    *)
      map="${method}"
      eval "destination_subpath=\${$map[\$file_tag]}"
      ;;
    esac

    # Ensure destination_dir is valid
    if [[ -n "$destination_subpath" ]]; then
      destination_dir="$output_directory/$destination_subpath"
    else
      destination_dir="$output_directory/others"
    fi

    if [ ! -d "$destination_dir" ]; then
      mkdir -p "$destination_dir"
    fi

    # Check if the file already exists in the destination
    if [[ -e "$destination_dir/$filename" ]]; then
      if [ "$DRYMODE" = "true" ]; then
        if [ "$KILLDUPLICATE" = "true" ]; then
          echo "Duplicate file: '$filename' removed"
        else
          echo "File '$filename' already exists in '$destination_dir'! Possible duplicate?"
        fi
      else
        if [ "$KILLDUPLICATE" = "true" ]; then
          rm "$file"
          echo "Duplicate file: '$filename' removed"
        else
          echo "File '$filename' already exists in '$destination_dir'! Possible duplicate?"
        fi
      fi
      continue
    fi

    # Move the file
    if [ "$DRYMODE" = "true" ]; then
      echo "Move file: $file ==> $destination_dir"
    else
      if mv -n "$file" "$destination_dir" 2>"$logs"; then
        echo "Moved '$filename' to '$destination_dir'"
      else
        echo "Error moving '$filename' to '$destination_dir'.  Check '$logs' for details." >&2
      fi
    fi
  done
  echo "Complete!"
}

function main() {
  if [ "$DRYMODE" = "true" ]; then
    echo "Dry Mode:"
  fi
  move
}

while [[ "$1" != "" ]]; do
  case "$1" in
  -d | --dry)
    DRYMODE=true
    shift
    ;;
  -r | --rm)
    KILLDUPLICATE=true
    shift
    ;;
  -dr | -rd)
    DRYMODE=true
    KILLDUPLICATE=true
    shift
    ;;
  -h | --help)
    help
    exit 0
    ;;
  *)
    if [[ -z "$method" ]]; then
      method="$1"
    elif [[ -z "$src_directory" ]]; then
      src_directory="$1"
    elif [[ -z "$output_directory" ]]; then
      output_directory="$1"
    else
      echo "Error: Unexpected argument '$1'"
      help
      exit 1
    fi
    shift
    ;;
  esac
done

# Check required arguments
if [[ -z "$method" || -z "$src_directory" || -z "$output_directory" ]]; then
  echo "Error: Missing required arguments."
  help
  exit 1
fi

# Same directory warning
if [ "$src_directory" == "$output_directory" ]; then
  echo "Be careful! You are running this script in the same directory!"
  echo "If this directory is overpopulated, it may take longer"
  select choice_continue in "Yes" "No"; do
    case $choice_continue in
    Yes) break ;;
    No) exit 0 ;;
    esac
  done
fi

# Check for config files and source them
if [[ ! -f "$config" ]]; then
  echo "Error: forg.conf not found.  Exiting." >&2
  exit 1
else
  # shellcheck disable=SC1090
  source "$config"
  val=$?
  if [ "$val" -ne 0 ]; then
    echo "Failed to source configuration files"
    exit 1
  fi
fi

main
